// <auto-generated />
using System;
using FluxoCaixa.Consolidation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FluxoCaixa.Consolidation.Infrastructure.Migrations
{
    [DbContext(typeof(DailyConsolidationDbContext))]
    [Migration("20260513200917_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FluxoCaixa.Consolidation.Domain.Entities.DailyBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<decimal>("TotalCredits")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_credits");

                    b.Property<decimal>("TotalDebits")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_debits");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ux_daily_balances_merchant_date");

                    b.ToTable("daily_balances", (string)null);
                });

            modelBuilder.Entity("FluxoCaixa.Consolidation.Infrastructure.Persistence.ProcessedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_processed_messages_event_id");

                    b.ToTable("processed_messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
